messages:
  folderPath: classpath:messages
  encoding: UTF-8
  file:
    common: messages
    error: errorMessages

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mibe
      username: "${MONGO_INITDB_ROOT_USERNAME}"
      password: "${MONGO_INITDB_ROOT_PASSWORD}"
      authentication-database: admin
  output:
    ansi:
      enabled: ALWAYS
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  show-actuator: true
  use-management-port: true
  swagger-ui:
    path: /docs/swagger-ui
  api-docs:
    path: /docs/v3/api

management:
  endpoints:
    web:
      exposure:
        include: openapi, swaggerui
  server:
    port: 9090

mqtt:
  enabled: true
  host: localhost

thinker:
  ble:
    rssiThreshold: -120
    rediscoveryTimeout: 20