messages:
  folderPath: classpath:messages
  encoding: UTF-8
  file:
    common: messages
    error: errorMessages

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mibe
      username: root
      password: root
      authentication-database: admin

springdoc:
  show-actuator: true
  use-management-port: true
  swagger-ui:
    path: /swagger-doc/swagger-ui
  api-docs:
    path: /swagger-doc/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: openapi, swaggerui
  server:
    port: 9090

thinker:
  ble:
    rssiThreshold: -120
    rediscoveryTimeout: 20