messages:
  folderPath: classpath:messages
  encoding: UTF-8
  file:
    common: messages
    error: errorMessages

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mibe
      username: root
      password: root
      authentication-database: admin

thinker:
  ble:
    rssiThreshold: -120